#!/usr/bin/env python3
"""Writes SAT flashcards and tutorials to assets/sat/."""
import json

def card(i, deck, subject, front, back, hint):
    return {"id": f"sfc-{i:03d}", "deck": deck, "subject": subject, "front": front, "back": back, "hint": hint}

M, V, G = "SAT Math Formulas", "SAT Vocabulary in Context", "SAT Grammar & Punctuation"
cards_raw = [
 (M,"satmath","Slope of a line through (x₁, y₁) and (x₂, y₂)","m = (y₂ − y₁) / (x₂ − x₁)","Rise over run."),
 (M,"satmath","Slope-intercept form of a line","y = mx + b, where m is the slope and b is the y-intercept.","b is where the line crosses the y-axis."),
 (M,"satmath","Quadratic formula","x = [−b ± √(b² − 4ac)] / 2a for ax² + bx + c = 0","Starts with negative b."),
 (M,"satmath","Discriminant and number of real solutions","b² − 4ac > 0: two real solutions; = 0: one; < 0: none.","Look under the square root."),
 (M,"satmath","Vertex form of a parabola","y = a(x − h)² + k has vertex (h, k); it is a minimum if a > 0 and a maximum if a < 0.","The sign inside the parentheses flips."),
 (M,"satmath","Distance between two points","d = √[(x₂ − x₁)² + (y₂ − y₁)²]","It is just the Pythagorean theorem."),
 (M,"satmath","Midpoint of a segment","((x₁ + x₂)/2, (y₁ + y₂)/2)","Average the coordinates."),
 (M,"satmath","Equation of a circle","(x − h)² + (y − k)² = r², center (h, k), radius r.","The right side is r squared."),
 (M,"satmath","Area and circumference of a circle","A = πr²; C = 2πr","The SAT reference sheet gives these, but know them cold."),
 (M,"satmath","Arc length and sector area","Arc = (θ/360)(2πr); Sector = (θ/360)(πr²)","Fraction of the full circle."),
 (M,"satmath","Degrees ↔ radians","radians = degrees × π/180; degrees = radians × 180/π","π radians = 180°."),
 (M,"satmath","Volume of a cylinder, cone, sphere","Cylinder πr²h; cone (1/3)πr²h; sphere (4/3)πr³","Cone is a third of the cylinder."),
 (M,"satmath","Special right triangles","30-60-90: sides x, x√3, 2x. 45-45-90: sides x, x, x√2.","Short leg, long leg, hypotenuse."),
 (M,"satmath","Right-triangle trig ratios","sin = opposite/hypotenuse; cos = adjacent/hypotenuse; tan = opposite/adjacent","SOH-CAH-TOA."),
 (M,"satmath","Exponential growth model","y = a(1 + r)^t for growth, y = a(1 − r)^t for decay.","a is the starting amount."),
 (M,"satmath","Percent change","(new − old) / old × 100","Always divide by the original."),
 (M,"satmath","Mean, median, and mode","Mean = sum ÷ count; median = middle value of the sorted list; mode = most frequent value.","Outliers pull the mean more than the median."),
 (M,"satmath","Probability of an event","favorable outcomes ÷ total outcomes","Always between 0 and 1."),
 (M,"satmath","Systems with no solution or infinitely many","Parallel lines (same slope, different intercept): no solution. Same line: infinitely many.","Compare slopes first."),
 (M,"satmath","Factoring a difference of squares","a² − b² = (a − b)(a + b)","Two perfect squares with a minus sign."),
 (V,"satrw","Ambivalent","Having mixed or conflicting feelings about something.","Think 'both ways.'"),
 (V,"satrw","Candid","Frank and honest, even when the truth is unwelcome.","A candid camera shows real life."),
 (V,"satrw","Ephemeral","Lasting only a very short time.","Like a mayfly."),
 (V,"satrw","Pragmatic","Dealing with things in a practical, realistic way.","Practical."),
 (V,"satrw","Meticulous","Showing great attention to detail; very careful.","Meticulous editors catch every comma."),
 (V,"satrw","Substantiate","To provide evidence that supports a claim.","Substance = proof."),
 (V,"satrw","Pivotal","Of crucial importance; a turning point.","Think 'pivot.'"),
 (V,"satrw","Undermine","To weaken gradually or secretly.","Dig under the foundation."),
 (V,"satrw","Tenuous","Very weak or slight; flimsy.","Related to 'thin.'"),
 (V,"satrw","Conciliatory","Intended to calm or make peace with someone.","Reconcile."),
 (V,"satrw","Equivocal","Open to more than one interpretation; deliberately vague.","'Equi' = equal voices."),
 (V,"satrw","Scrutinize","To examine closely and critically.","Look under a magnifying glass."),
 (V,"satrw","Corroborate","To confirm or give support to a statement with additional evidence.","Co- + robust."),
 (V,"satrw","Prudent","Acting with care and thought for the future.","Prudent savers keep an emergency fund."),
 (V,"satrw","Laconic","Using very few words.","Sparta's Laconia was famous for short answers."),
 (G,"satrw","Two independent clauses: how to join them","Use a period, a semicolon, a colon (if the second explains the first), or a comma plus a FANBOYS conjunction.","A lone comma is always a splice."),
 (G,"satrw","Nonessential (extra) information","Set it off with a pair of commas, dashes, or parentheses; never use just one.","Test: remove it. If the sentence still works, it's nonessential."),
 (G,"satrw","Colon rule","A colon must follow a complete sentence.","Never put a colon right after a verb or preposition."),
 (G,"satrw","Subject–verb agreement through interruptions","Ignore phrases set off by commas or beginning with 'along with', 'as well as', 'in addition to'.","Find the true subject."),
 (G,"satrw","Pronoun agreement","A pronoun must match its antecedent in number: 'The company raised its prices.'","Collective nouns are usually singular."),
 (G,"satrw","Modifier placement","A descriptive phrase must sit next to the noun it describes: 'Walking home, I saw...' not 'Walking home, the rain started.'","Who is doing the action?"),
 (G,"satrw","Its vs. it's; their vs. they're","Its = possessive; it's = it is. Their = possessive; they're = they are.","Expand the contraction to test it."),
 (G,"satrw","Verb tense consistency","Keep tenses logical for the timeline; use past perfect for an action that happened before another past action.","Look at time clues."),
 (G,"satrw","Comparatives vs. superlatives","Compare two items with -er/more; three or more with -est/most.","Of the two → comparative."),
 (G,"satrw","Transitions: contrast, cause, addition","Contrast: however, yet, by contrast. Cause/effect: therefore, as a result. Addition: moreover, in addition. Example: for instance.","Decide the relationship first, then pick the word."),
]
cards = [card(i, *c[:1], *c[1:]) if False else card(i+1, c[0], c[1], c[2], c[3], c[4]) for i, c in enumerate(cards_raw)]

def tut(id, subject, cat, title, symbol, summary, mins, sections, facts, examples, tips):
    return {"id": id, "subject": subject, "category": cat, "title": title, "symbolName": symbol,
            "summary": summary, "estimatedMinutes": mins,
            "sections": [{"heading": h, "body": b} for h, b in sections],
            "keyFacts": facts,
            "examples": [{"problem": p, "steps": s, "answer": a} for p, s, a in examples],
            "tips": tips}

tutorials = [
 tut("sat-m1","satmath","Algebra","Linear Equations & Systems","function",
  "Solve, graph, and interpret linear relationships, the largest single topic on the SAT Math section.",7,
  [("The Core Idea","Linear equations describe a constant rate of change. In y = mx + b, m tells you how much y changes each time x increases by 1, and b is the value of y when x is 0. Most SAT word problems hide a line: a fixed fee plus a per-item rate, a starting balance plus a monthly deposit. Translating the words into y = mx + b is half the work."),
   ("Systems of Equations","Two lines can intersect once (one solution), never (parallel, same slope but different intercepts), or everywhere (the same line). To solve, use substitution when one variable is already isolated and elimination when coefficients line up. On the SAT you can also use the graphing calculator built into the test to find the intersection quickly, but always sanity-check the answer.")],
  ["Slope = (y₂ − y₁)/(x₂ − x₁)","Parallel lines share a slope; perpendicular slopes are negative reciprocals.","No solution: same slope, different intercept. Infinite solutions: identical equations.","The constant term is the starting value; the coefficient of x is the rate."],
  [("A gym charges a $40 sign-up fee plus $25 per month. After how many months does a member's total cost reach $190?",["Write 40 + 25m = 190.","Subtract 40: 25m = 150.","Divide by 25: m = 6."],"6 months"),
   ("Solve the system: 2x + y = 11 and x − y = 1.",["Add the equations: 3x = 12, so x = 4.","Substitute into x − y = 1: 4 − y = 1, so y = 3."],"x = 4, y = 3")],
  ["Define your variables in words before writing equations.","Check your answer by plugging it back into the original problem.","If a question asks for 'x + y' or '2x', solve for that expression directly when you can."]),
 tut("sat-m2","satmath","Advanced Math","Quadratics & Functions","chart",
  "Factor, complete the square, read parabolas, and work with function notation.",8,
  [("Quadratics","A quadratic has the form ax² + bx + c. You can solve it by factoring, completing the square, or the quadratic formula. The discriminant b² − 4ac tells you how many real solutions exist: positive means two, zero means one, negative means none. In vertex form, y = a(x − h)² + k, the vertex is (h, k), and the sign of a tells you whether it opens up or down."),
   ("Function Notation","f(3) means 'substitute 3 for x.' For composition, f(g(x)), work from the inside out: evaluate g first, then feed the result into f. Transformations: f(x) + k shifts up, f(x − h) shifts right, and −f(x) reflects across the x-axis.")],
  ["Sum of roots = −b/a; product of roots = c/a.","Difference of squares: a² − b² = (a − b)(a + b).","Perfect-square trinomial: a² + 2ab + b² = (a + b)².","Exactly one real solution when b² − 4ac = 0."],
  [("If f(x) = 2x + 3 and g(x) = x² − 1, what is f(g(3))?",["g(3) = 9 − 1 = 8.","f(8) = 2(8) + 3 = 19."],"19"),
   ("For what positive value of k does x² + kx + 25 = 0 have exactly one solution?",["Set the discriminant to 0: k² − 4(25) = 0.","k² = 100, so k = 10."],"10")],
  ["When a quadratic is hard to factor, try the quadratic formula or the calculator's graph.","Know the three forms (standard, factored, vertex) and what each reveals.","In composition, never reverse the order."]),
 tut("sat-m3","satmath","Problem-Solving & Data Analysis","Percents, Ratios & Data","chart",
  "Percent change, unit conversion, statistics, and reading tables and scatterplots.",7,
  [("Percents and Rates","'Percent of' means multiply; 'percent change' means (new − old)/old. A successive increase and decrease are not inverses: raising a price 20% and then lowering it 20% leaves it 4% lower. Unit conversions are multiplication by fractions equal to 1, like (5,280 feet / 1 mile), arranged so the unwanted unit cancels."),
   ("Statistics and Data","The mean is sensitive to outliers; the median is not. Standard deviation measures spread, so a data set with a larger standard deviation is more spread out. A line of best fit gives a prediction, not a certainty, and correlation does not prove causation. Always check what a table or graph is actually measuring before answering.")],
  ["Percent change = (new − old) / old × 100.","Compound growth: A = P(1 + r)^t.","Mean of a data set = sum ÷ count.","A random sample generalizes only to the population it was drawn from."],
  [("A $50 item increases 20% and then decreases 20%. What is the final price?",["After the increase: 50 × 1.2 = 60.","After the decrease: 60 × 0.8 = 48."],"$48")],
  ["Convert percentages to decimals before multiplying.","In table problems, circle the exact group the question asks about.","Check units at the end."]),
 tut("sat-m4","satmath","Geometry & Trigonometry","Geometry & Trigonometry Essentials","triangle",
  "Triangles, circles, volume, and right-triangle trigonometry.",7,
  [("Triangles and Circles","The angles of a triangle sum to 180°. In a right triangle, a² + b² = c². Special right triangles (30-60-90 and 45-45-90) have fixed side ratios. A circle's equation is (x − h)² + (y − k)² = r², and the arc and sector of a central angle θ are (θ/360) of the circumference and area respectively."),
   ("Trigonometry","SOH-CAH-TOA connects an angle to a ratio of sides. Complementary angles satisfy sin(x) = cos(90° − x). Radians measure angles by arc length: π radians equals 180°. To convert, multiply degrees by π/180.")],
  ["Pythagorean triples: 3-4-5, 5-12-13, 8-15-17, 7-24-25.","Similar triangles have equal angles and proportional sides.","Arc length = (θ/360)(2πr).","sin A = cos B when A and B are the acute angles of a right triangle."],
  [("A circle has radius 6. What is the arc length intercepted by a 60° central angle?",["Arc = (60/360)(2π × 6).","= (1/6)(12π) = 2π."],"2π")],
  ["Draw and label the figure, even if one is provided.","Look for special triangles before using the Pythagorean theorem.","Keep π in your answer unless a decimal is requested."]),
 tut("sat-r1","satrw","Craft & Structure","Words in Context & Vocabulary","book",
  "Choose the most precise word by using the clues the passage gives you.",6,
  [("Predict, Then Match","Cover the answer choices and read the sentence. Ask: what must the blank mean, based on the clues? Look for contrast words (although, but, rather than) and for examples that define the blank. Predict a simple word of your own, and then choose the answer closest in meaning and tone."),
   ("Precision Matters","Several choices may have a similar general meaning. The right one fits the exact context, including degree and connotation. 'Careful' and 'meticulous' are close, but 'meticulous' is stronger. A word that sounds sophisticated is not better if it does not match the clue.")],
  ["Use context clues: definitions, examples, contrasts, and cause-effect.","Watch the tone: positive, negative, or neutral.","Eliminate choices that contradict a clue.","Plug your final choice back in and reread."],
  [("Although critics called the early drafts ______, the final version was praised for its clarity. (opaque / lucid / brief / ornate)",["'Although' signals a contrast with 'clarity.'","The blank must mean the opposite of clear: opaque."],"opaque")],
  ["Do not choose a word just because you know it.","If two choices seem right, look for the more specific clue.","Practice vocabulary through reading, not just flashcards."]),
 tut("sat-r2","satrw","Standard English Conventions","Punctuation & Sentence Boundaries","pencil",
  "The commas, semicolons, colons, and dashes that appear in nearly every Writing question set.",8,
  [("Boundaries","The SAT tests whether you can join, separate, and interrupt sentences correctly. Two independent clauses (each could stand alone) need a period, a semicolon, a colon (when the second explains the first), or a comma with a conjunction. A comma alone creates a splice. Dependent clauses and phrases lead into a main clause with a comma."),
   ("Extra Information and Lists","Nonessential information is surrounded by matching punctuation: two commas, two dashes, or parentheses. Never mix them or use only one. A colon must follow a complete sentence; do not place it directly after a verb or preposition. In a series, commas separate items; if the items contain commas, use semicolons.")],
  ["Independent + independent: period, semicolon, colon, or comma + FANBOYS.","Nonessential phrases come in pairs of punctuation.","No comma between a subject and its verb, or between a verb and its object.","Colon = after a complete sentence."],
  [("The bridge, which opened in 1932 ______ remains one of the busiest in the country. Which punctuation completes the sentence?",["'which opened in 1932' is nonessential and was opened with a comma.","It must be closed with a comma before the verb 'remains.'"],"a comma")],
  ["Cover the extra information. Does the sentence still work?","Look for one comma where a pair belongs.","Do not add a comma just because you hear a pause."]),
 tut("sat-r3","satrw","Expression of Ideas","Transitions & Rhetorical Synthesis","list",
  "Choose the logical transition and the note-based sentence that best achieves a stated goal.",6,
  [("Transitions","First decide the relationship between the two sentences: contrast (however, yet), cause (therefore, as a result), addition (moreover, in addition), example (for instance), or sequence (later, next). Then choose the transition that matches. Never pick a transition just because it sounds formal."),
   ("Rhetorical Synthesis","You receive a bulleted list of notes and a goal such as 'emphasize the contrast' or 'introduce the topic to an audience unfamiliar with it.' The correct answer uses only the notes relevant to the goal and states them clearly. Reread the goal, and eliminate answers that use true but irrelevant information.")],
  ["Contrast: however, yet, by contrast, nevertheless.","Cause/effect: therefore, as a result, consequently.","Addition: moreover, in addition, furthermore.","The goal tells you which notes matter."],
  [("Wind turbines produce power without fuel. ______ they can harm birds if poorly placed. Which transition fits?",["The second sentence names a drawback, contrasting with the benefit.","'However' signals the contrast."],"However,")],
  ["Underline the goal in the question.","Ignore details that do not serve the goal, however interesting.","Read each transition in the sentence before deciding."]),
 tut("sat-r4","satrw","Information & Ideas","Central Ideas, Evidence & Inferences","magnifier",
  "Find the main point, choose the best supporting evidence, and make safe inferences.",7,
  [("Central Ideas and Details","The central idea is the point of the whole passage, not any single detail. Summarize in your own words before looking at the choices. Wrong choices are often too narrow (a detail), too broad (beyond the passage), or distorted (a twisted reading). For detail questions, find the exact line in the text."),
   ("Evidence and Inferences","For command of evidence, the correct choice directly supports (or weakens) the specific claim, not a related topic. For inference questions, the answer must be supported by the text; if it requires outside assumptions, it is wrong. Treat the passage as the only source of truth.")],
  ["Main idea = whole passage; detail = one part.","Extreme words (always, never, only) are often wrong.","The best evidence matches the claim's exact wording.","An inference must follow from the text alone."],
  [("Researchers found that plants in moving air grew thicker stems. Which conclusion is best supported? (a) Plants need fans. (b) Gentle air movement may strengthen stems.",["Only (b) follows directly from the single difference (moving air).","(a) is too extreme."],"(b)")],
  ["Prove the answer with a line from the text.","Beware answers that are true in real life but not stated in the passage.","For evidence questions, restate the claim in your own words first."]),
]

import os
os.makedirs("assets/sat/study", exist_ok=True)
json.dump(cards, open("assets/sat/study/flashcards.json", "w"), indent=1, ensure_ascii=False)
json.dump(tutorials, open("assets/sat/tutorials/sat_tutorials.json", "w"), indent=1, ensure_ascii=False)
print(len(cards), "cards,", len(tutorials), "tutorials")
