# Original SAT-style Reading & Writing items, part 1:
# Craft & Structure, Information & Ideas.
# Tuple: (topic, difficulty, stimulus, prompt, correct, [three wrong], explanation)

WIC = "Words in Context"
TSP = "Text Structure & Purpose"
CTC = "Cross-Text Connections"
CID = "Central Ideas & Details"
COE = "Command of Evidence"
INF = "Inferences"

BLANK = "Which choice completes the text with the most logical and precise word or phrase?"

PART1 = [
    # ---------------------------------------------------------- Words in Context
    (WIC, 1, "Although the mayor's first proposal was widely criticized, her revised plan was received so ______ that the council approved it within a week.",
     BLANK, "enthusiastically", ["reluctantly", "indifferently", "suspiciously"],
     "The council approved the plan within a week, which signals a warm reception. 'Enthusiastically' fits; the other choices suggest hesitation or disinterest."),
    (WIC, 2, "Marine biologist Dr. Lena Okafor describes the deep-sea anglerfish as a(n) ______ predator: it lies motionless in the dark for hours, relying on a glowing lure to draw prey close rather than chasing it.",
     BLANK, "patient", ["frantic", "gregarious", "reckless"],
     "Lying motionless and waiting for prey to approach describes a patient hunter. 'Frantic' and 'reckless' contradict the stillness."),
    (WIC, 2, "Many of the poet's early admirers found her work ______; its dense references to obscure myths made even short poems difficult to follow without a commentary.",
     BLANK, "impenetrable", ["transparent", "tedious", "uplifting"],
     "Dense, obscure references that require commentary make the poems hard to understand: 'impenetrable.' 'Transparent' means the opposite."),
    (WIC, 3, "The botanist's findings were initially met with ______ by colleagues, who doubted that a plant could survive in such salty soil; only after three independent labs repeated the experiment did the skepticism fade.",
     BLANK, "skepticism", ["acclaim", "relief", "sympathy"],
     "The colleagues 'doubted' the claim and the passage later says 'the skepticism fade[d],' so 'skepticism' is the best fit."),
    (WIC, 1, "The museum's new exhibit is ______ to visitors of all ages: young children enjoy its interactive displays, while adults appreciate its detailed historical research.",
     BLANK, "appealing", ["unfamiliar", "irrelevant", "confusing"],
     "Both children and adults enjoy different aspects of the exhibit, so it is appealing to everyone."),
    (WIC, 2, "In her memoir, the former diplomat is surprisingly ______ about her failures, describing missed opportunities and poor judgment calls in unsparing detail.",
     BLANK, "candid", ["evasive", "boastful", "sentimental"],
     "'Unsparing detail' about failures indicates honesty. 'Candid' means frank; 'evasive' means the opposite."),
    (WIC, 3, "Historians have long regarded the treaty as a ______ event: before it, the two nations had fought for decades; afterward, they never again went to war.",
     BLANK, "pivotal", ["trivial", "predictable", "controversial"],
     "A single event that cleanly divides a long period of war from lasting peace is 'pivotal.' Nothing in the text suggests controversy or triviality."),
    (WIC, 2, "Because the hikers had underestimated how much water they would need, the remaining supply was ______, forcing them to turn back a full day early.",
     BLANK, "inadequate", ["abundant", "contaminated", "unnecessary"],
     "The hikers were forced to turn back, so the water was insufficient: 'inadequate.'"),
    (WIC, 3, "The architect's design is notable for its ______: every element, from the width of the doorways to the angle of the roof, serves a clear function, and nothing is merely ornamental.",
     BLANK, "economy", ["extravagance", "ambiguity", "whimsy"],
     "A design in which nothing is merely ornamental and each element serves a purpose shows 'economy.' 'Extravagance' and 'whimsy' contradict that."),
    (WIC, 1, "The newspaper issued a correction after readers pointed out that an article had ______ the date of the festival, listing it as June 4 instead of June 14.",
     BLANK, "misreported", ["celebrated", "postponed", "illustrated"],
     "The article gave the wrong date, so it 'misreported' it."),
    (WIC, 2, "Researchers at the observatory were ______ the new data, spending weeks checking each measurement against earlier records before announcing their conclusions.",
     BLANK, "scrutinizing", ["ignoring", "inventing", "applauding"],
     "Checking each measurement against earlier records is careful examination, i.e., scrutinizing."),
    (WIC, 3, "The playwright's later works are marked by a ______ tone that surprised critics accustomed to the sharp satire of her early plays; they read as gentle, even forgiving, portraits of ordinary people.",
     BLANK, "conciliatory", ["acerbic", "frenetic", "menacing"],
     "The later works are 'gentle, even forgiving,' contrasting with sharp satire. 'Conciliatory' (inclined to make peace) fits; 'acerbic' means harsh."),
    (WIC, 2, "Although the study's sample size was small, its authors argue that the results are still ______ because the same pattern appeared in every one of the twelve cities examined.",
     BLANK, "significant", ["unreliable", "accidental", "discouraging"],
     "The consistent pattern across all cities supports the claim that the results matter, so 'significant' fits."),
    (WIC, 1, "The software update was ______ for most users, who noticed no change in how the app worked except that it loaded a little faster.",
     BLANK, "seamless", ["disastrous", "optional", "expensive"],
     "Users noticed almost no change, so the update was smooth, or seamless."),
    (WIC, 3, "Critics describe the novelist's prose as ______: she conveys complicated emotions in sentences so spare that a reader may pass over their force on a first reading.",
     BLANK, "understated", ["ornate", "bombastic", "careless"],
     "Spare sentences that convey strong feeling quietly are 'understated.' 'Ornate' and 'bombastic' describe the opposite style."),
    (WIC, 2, "Rather than ______ the committee's concerns, the director addressed each one in turn and revised the proposal accordingly.",
     BLANK, "dismissing", ["acknowledging", "documenting", "repeating"],
     "'Rather than' sets up a contrast with addressing each concern, so the missing word means to wave them away: 'dismissing.'"),
    (WIC, 3, "The ecologist cautions that the recovery of the wetland, though encouraging, is still ______: a single dry summer could undo years of restoration work.",
     BLANK, "tenuous", ["permanent", "exaggerated", "complete"],
     "If one dry summer could undo the progress, the recovery is fragile, or 'tenuous.'"),
    (WIC, 1, "The chef's menu changes with the seasons, ______ whatever ingredients the local farms have in abundance at that time of year.",
     BLANK, "reflecting", ["rejecting", "forgetting", "delaying"],
     "A menu that changes with the harvest reflects what is available locally."),
    (WIC, 2, "During the debate, the senator's argument was undermined when her opponent produced records that ______ her claim that spending had fallen every year.",
     BLANK, "contradicted", ["supported", "clarified", "predicted"],
     "Records that undermine her argument would contradict, not support, her claim."),
    (WIC, 3, "The documentary's narrator maintains a ______ attitude toward the explorer, neither praising his achievements nor condemning his mistakes, but presenting both without comment.",
     BLANK, "neutral", ["adulatory", "scornful", "apprehensive"],
     "Presenting both successes and mistakes 'without comment' indicates neutrality."),

    # ------------------------------------------------- Text Structure & Purpose
    (TSP, 2, "Octopuses are famous escape artists. Keepers at one aquarium once found an octopus's tank empty each morning, only to discover that it was sneaking out at night to feed on fish in a neighboring tank before returning to its own.",
     "Which choice best describes the function of the second sentence in the text as a whole?",
     "It offers a specific example that illustrates the claim made in the first sentence.",
     ["It introduces a counterargument to the claim made in the first sentence.", "It defines a technical term used in the first sentence.", "It shifts the focus from octopuses to aquarium management."],
     "The first sentence makes a general claim (octopuses escape); the second gives a concrete case of it."),
    (TSP, 2, "The city's bike-share program was supposed to reduce car traffic downtown. Yet traffic counts have barely changed since the program launched. Planners now suspect that many riders are simply replacing walking or bus trips, not driving trips.",
     "Which choice best states the main purpose of the text?",
     "To present a possible explanation for why a program has not produced its intended result",
     ["To argue that bike-share programs should be eliminated", "To compare the benefits of walking with those of cycling", "To describe how bike-share programs are funded"],
     "The text states an expectation, notes that it was not met, and offers planners' hypothesis for why."),
    (TSP, 3, "When physicist Hana Voss began studying how snow insulates the ground, most colleagues assumed that the topic was too narrow to matter. But her measurements showed that a thick snowpack can keep soil tens of degrees warmer than the air above it, a finding that has since reshaped how scientists model Arctic carbon release.",
     "Which choice best describes the overall structure of the text?",
     "It describes an initial assumption, then presents evidence that overturned it and notes the finding's impact.",
     ["It lists several unrelated findings and then ranks them by importance.", "It presents a problem, rejects two proposed solutions, and recommends a third.", "It compares two research methods and concludes that neither is reliable."],
     "Colleagues first assumed the topic was minor ('too narrow'); the 'But' sentence gives evidence against that and notes consequences."),
    (TSP, 1, "Dear neighbors: The community garden will close for repairs from March 3 to March 17. During this time, please do not enter the fenced area. We expect to reopen on March 18 and will plant new beds in April.",
     "Which choice best describes the main purpose of the text?",
     "To inform a community of a temporary closure and when it will end",
     ["To persuade neighbors to donate money for repairs", "To describe the history of the garden", "To criticize the way the garden has been maintained"],
     "The notice gives the closure dates, an instruction, and a reopening date."),
    (TSP, 2, "Poet Marguerite Dane is often associated with the city of Boston, yet she wrote some of her best-known early poems while traveling at sea as a ship's crewman. The ocean, with its steady rhythms, may have shaped the music of her lines more than any city street did.",
     "Which choice best describes the function of the underlined portion, 'yet she wrote some of her best-known early poems while traveling at sea as a ship's crewman'?",
     "It introduces a fact that complicates a common association.",
     ["It provides evidence that Dane disliked Boston.", "It defines the term 'crewman.'", "It summarizes the poems Hughes wrote at sea."],
     "'Yet' signals contrast: the common Harlem association is complicated by the fact that many early poems were written at sea."),
    (TSP, 3, "Economists often treat leisure time as wasted output. But a growing body of research suggests that people who take regular breaks solve problems faster and make fewer errors. If so, a schedule packed with uninterrupted work may reduce, rather than raise, a team's total productivity.",
     "Which choice best describes the function of the last sentence?",
     "It draws a conclusion that follows from the research just described.",
     ["It restates the economists' view in different words.", "It gives an example of a team that succeeded without breaks.", "It questions whether the research methods were sound."],
     "'If so' signals an inference from the research; it concludes that constant work may lower productivity."),
    (TSP, 2, "The following is from a field guide: The red-tailed hawk is the most common hawk in North America. Look for its rust-colored tail, which is visible when the bird soars overhead. In winter, it often perches on roadside poles, scanning the ground for rodents.",
     "Which choice best describes the main purpose of the text?",
     "To help readers identify a bird and know where they might see it",
     ["To explain why hawks are declining in number", "To compare hawks with other predators", "To argue that hawks should be protected"],
     "The passage gives identifying features and typical locations, as a field guide does."),
    (TSP, 3, "In 1928, Alexander Fleming noticed that mold had killed bacteria on one of his discarded dishes. Many scientists might have thrown the dish away; Fleming instead investigated, and his curiosity led to the discovery of penicillin. His story is often told as a tale of luck, but it is just as much a tale of attentiveness.",
     "Which choice best describes the overall structure of the text?",
     "It recounts an event, then offers a reframing of how the event is usually understood.",
     ["It presents a hypothesis and then tests it with an experiment.", "It lists the steps in a scientific process in order.", "It contrasts two scientists with opposing views."],
     "The narrative of Fleming's observation is followed by a final sentence that reinterprets it as attentiveness, not just luck."),
    (TSP, 1, "Rain gardens are shallow gardens planted with native grasses and flowers. They collect runoff from roofs and driveways and let it soak into the ground slowly, which reduces flooding and filters pollutants before they reach streams.",
     "Which choice best describes the main purpose of the text?",
     "To explain what rain gardens are and what they do",
     ["To argue that all homeowners should build rain gardens", "To describe how to choose native plants", "To compare rain gardens with swimming pools"],
     "The text defines rain gardens and explains their function."),
    (TSP, 2, "Some linguists argue that a language dies when its last fluent speaker does. But in Wales, activists have shown that a language with few native speakers can recover when schools, television, and public signs all use it. Revival, it turns out, depends less on the number of speakers than on the number of places where the language is needed.",
     "Which choice best describes the function of the second sentence?",
     "It presents a case that challenges the view stated in the first sentence.",
     ["It restates the view in the first sentence using more precise terms.", "It provides a definition of 'fluent speaker.'", "It introduces a new topic unrelated to the first sentence."],
     "The second sentence uses Wales as a counterexample to the claim that a language is doomed once speakers dwindle."),

    # ------------------------------------------------------ Cross-Text Connections
    (CTC, 2, "Text 1: Urban planners often claim that wide sidewalks encourage walking. Text 2: In a survey of eight cities, researcher Mina Park found that sidewalk width had almost no relationship to how much people walked; instead, the presence of shops and cafés within a five-minute stroll predicted walking rates much better.",
     "Based on the texts, how would Park (Text 2) most likely respond to the claim in Text 1?",
     "By arguing that other features of a neighborhood matter more than sidewalk width",
     ["By agreeing that wide sidewalks are the best way to increase walking", "By suggesting that cities should remove sidewalks entirely", "By claiming that people do not like to walk in cities"],
     "Park's data show sidewalk width barely matters and nearby destinations matter more."),
    (CTC, 3, "Text 1: Critic A argues that the film's slow pacing is a flaw, since it asks viewers to wait through long silent scenes with little plot. Text 2: Critic B writes that the same silent scenes are the film's greatest strength because they let viewers feel the characters' isolation.",
     "Which choice best describes the relationship between the two texts?",
     "Both critics notice the same feature of the film but judge its effect differently.",
     ["Critic B provides evidence that supports Critic A's argument.", "Critic A and Critic B discuss entirely different films.", "Critic B summarizes the plot that Critic A leaves out."],
     "Both refer to the long silent scenes; A sees a flaw and B sees a strength."),
    (CTC, 2, "Text 1: Many ecologists believe that reintroducing wolves to a park will restore its balance by controlling elk populations. Text 2: Biologist Reza Tehrani cautions that the effect on elk is only part of the story, because wolves also change where elk graze, which allows streamside plants to recover.",
     "Which choice best describes how Tehrani (Text 2) would most likely respond to the belief in Text 1?",
     "By agreeing that wolves matter but adding that their influence extends beyond population control",
     ["By denying that wolves have any effect on elk", "By insisting that wolves should not be reintroduced", "By arguing that elk populations are unimportant"],
     "Tehrani calls the elk effect 'only part of the story' and adds a second effect, so he extends rather than rejects the claim."),
    (CTC, 3, "Text 1: Historian Priya Nair argues that the printing press spread new ideas quickly because it made books cheap. Text 2: Historian Tom Aldous responds that cost alone cannot explain the speed, since literacy rates were low in many regions; he points to public readings in taverns, which let people absorb books without being able to read them.",
     "Based on the texts, what would Aldous (Text 2) most likely say about Nair's explanation?",
     "It is incomplete because it overlooks how people without literacy could still encounter books.",
     ["It is correct because cheap books reached everyone directly.", "It is irrelevant because printing presses were rare.", "It is unsupported because no books were printed in that era."],
     "Aldous accepts that cost mattered but says it 'cannot explain' the speed on its own and adds public readings."),
    (CTC, 1, "Text 1: Some teachers believe that students learn best when they sit in silent rows. Text 2: Education researcher Dana Lee found that students who discuss problems with a partner score higher on later tests than students who work alone in silence.",
     "Which choice best describes the relationship between the texts?",
     "Text 2 presents research that challenges the belief described in Text 1.",
     ["Text 2 repeats the belief described in Text 1.", "Text 2 offers a definition of the term in Text 1.", "Text 2 describes a different subject altogether."],
     "Lee's findings favor partner discussion over silent solo work, so they challenge the teachers' belief."),
    (CTC, 2, "Text 1: A food scientist claims that organic produce is always more nutritious than conventional produce. Text 2: A review of 40 studies by nutrition researcher Ali Haddad found small differences in some vitamins but concluded that, for most fruits and vegetables, the nutritional gap was too small to matter.",
     "Based on the texts, how would Haddad (Text 2) most likely characterize the claim in Text 1?",
     "As overstated, since the evidence shows only minor differences",
     ["As too modest, since the gap is larger than claimed", "As accurate in every respect", "As impossible to test"],
     "'Always more nutritious' is contradicted by a review finding small, mostly negligible differences."),
    (CTC, 3, "Text 1: Author Maria Soto praises the novel for its realistic dialogue, which she says captures how teenagers actually speak. Text 2: Linguist Ben Ito notes that the dialogue in the novel is full of slang that was already out of date when the book was published.",
     "Based on the texts, how would Ito (Text 2) most likely respond to Soto's praise (Text 1)?",
     "By questioning whether the dialogue is as realistic as Soto claims",
     ["By agreeing that the dialogue is perfectly realistic", "By praising the novel's plot instead", "By arguing that teenagers do not use slang"],
     "Ito's point that the slang was outdated undercuts the claim of realism."),
    (CTC, 2, "Text 1: Many cities are installing glass-walled bus shelters to make waiting riders feel safer. Text 2: In a study of 30 bus stops, transit analyst Colin Reyes found that riders felt safest at stops with good lighting and frequent buses, regardless of the shelter's walls.",
     "Which choice best describes the relationship between the texts?",
     "Text 2 suggests that the approach in Text 1 may not address the factors that matter most.",
     ["Text 2 shows that glass walls are the most effective safety measure.", "Text 2 argues that riders should avoid bus shelters.", "Text 2 describes how glass is manufactured."],
     "Reyes finds lighting and frequency matter more than walls, implying the cities' approach misses the key factors."),

    # --------------------------------------------------- Central Ideas & Details
    (CID, 1, "Honeybees communicate the location of food by dancing. A bee that has found nectar returns to the hive and performs a 'waggle dance' whose angle shows the direction of the food relative to the sun and whose duration shows its distance.",
     "Which choice best states the main idea of the text?",
     "Honeybees use dance movements to tell other bees where food is.",
     ["Honeybees prefer to travel in the direction of the sun.", "Honeybees cannot find food without a hive.", "Honeybees dance only when they are tired."],
     "The text explains that the dance conveys direction and distance of food."),
    (CID, 2, "For decades, the tiny island of Nauru was one of the richest nations per person because of its phosphate deposits. By the 1990s, however, the mines were nearly exhausted, and the nation, which had invested little in other industries, faced severe economic hardship.",
     "Which choice best states the main idea of the text?",
     "Nauru's reliance on a single resource left it vulnerable once that resource ran low.",
     ["Nauru has the largest phosphate deposits in the world.", "Nauru's economy has always been poor.", "Nauru's government banned mining in the 1990s."],
     "The text contrasts earlier wealth from phosphate with hardship after depletion and limited diversification."),
    (CID, 2, "Sea otters, which keep their young safe by wrapping them in kelp while they dive for food, are considered a 'keystone' species. By eating sea urchins, otters protect kelp forests from being overgrazed, and those forests in turn shelter hundreds of other species.",
     "According to the text, why are sea otters considered a keystone species?",
     "Their eating of sea urchins protects kelp forests that many other species depend on.",
     ["They are the largest animals in the kelp forest.", "They build shelters that other species use.", "They wrap their young in kelp."],
     "The text says otters eat urchins, which protects the kelp forests that shelter many species."),
    (CID, 3, "In the 1930s, labor economist Ruth Alder pushed for policies that many business leaders opposed, arguing that unemployment insurance would stabilize consumer spending during downturns. Critics warned that such programs would discourage work. Decades of data have since shown that benefit programs cushion economic shocks without producing the widespread withdrawal from work that critics predicted.",
     "Which choice best states the main idea of the text?",
     "Later evidence largely supported Alder's position rather than her critics' predictions.",
     ["Alder opposed all government programs.", "Business leaders were the first to support unemployment insurance.", "Unemployment insurance has no effect on spending."],
     "The final sentence says the data showed cushioning effects without the work withdrawal critics predicted."),
    (CID, 1, "The Great Wall of China is not a single wall but a series of walls built by different dynasties over many centuries. The best-known sections, made of stone and brick, date to the Ming dynasty, which ruled from 1368 to 1644.",
     "According to the text, which sections of the Great Wall are the best known?",
     "Those made of stone and brick during the Ming dynasty",
     ["Those built from a single wall in one century", "Those made of wood during the earliest dynasties", "Those built after 1644"],
     "The text says the best-known sections are stone and brick and date to the Ming dynasty."),
    (CID, 2, "Researchers who studied 200 elementary classrooms found that students whose teachers read aloud for just fifteen minutes a day gained vocabulary faster than students whose teachers did not, even after accounting for family income. The effect was largest for students who spoke another language at home.",
     "Which choice best states the main idea of the text?",
     "Daily read-aloud time in class was linked to faster vocabulary growth, especially for students who spoke another language at home.",
     ["Family income has no effect on vocabulary.", "Teachers should stop assigning reading homework.", "Students who speak another language at home are poor readers."],
     "The study found a vocabulary benefit from read-aloud time that was largest among students who spoke another language at home."),
    (CID, 3, "Mathematician Sophie Germain was barred from attending lectures at the École Polytechnique because she was a woman, so she obtained the lecture notes and submitted her work under a male pseudonym. Her insights into the theory of elasticity were so original that the leading mathematicians of the day sought out the mysterious 'author,' and the truth of her identity did not diminish their respect.",
     "Which choice best states the main idea of the text?",
     "Germain's talent earned respect from leading mathematicians despite barriers placed in her way.",
     ["Germain preferred to remain anonymous throughout her life.", "The École Polytechnique later admitted only women.", "Elasticity was a topic of little interest to mathematicians."],
     "She overcame exclusion by working under a pseudonym, and her work earned respect even once her identity was known."),
    (CID, 1, "A single mature oak tree can produce as many as ten thousand acorns in a good year. Most of these acorns are eaten by squirrels, deer, and birds, but the few that are buried and forgotten can grow into new trees.",
     "According to the text, how can an acorn grow into a new oak tree?",
     "It can be buried and forgotten by an animal.",
     ["It can be eaten by a deer.", "It can be picked up by a mature oak.", "It can be planted by a forest ranger."],
     "The text says the acorns that are buried and forgotten can grow."),
    (CID, 2, "Since the 1970s, the number of languages spoken in the Amazon basin has fallen sharply. Anthropologists attribute the decline less to deliberate suppression than to economic pressure: as families move to towns for work, children increasingly learn the regional trade language instead of their parents' tongue.",
     "According to the text, what do anthropologists identify as the main reason for the decline of Amazonian languages?",
     "Families moving to towns for work, so children learn a trade language",
     ["Laws that forbid the use of native languages", "A decline in the Amazon's population overall", "The invention of new writing systems"],
     "The text says economic pressure and migration, not deliberate suppression, drive the decline."),
    (CID, 3, "When volcanic ash blankets a landscape, it can smother plants and block sunlight, but it also releases minerals as it weathers. Ecologists studying a volcanic island found that, within ten years of an eruption, areas covered by thin layers of ash supported richer plant communities than nearby areas the ash had missed.",
     "Which choice best states the main idea of the text?",
     "Volcanic ash can harm plants initially but may ultimately enrich the soil.",
     ["Volcanic eruptions always destroy local ecosystems.", "Ash layers should be removed to help plants grow.", "The island has not erupted since."],
     "The text pairs the immediate harm with the later benefit from released minerals."),
    (CID, 1, "Dolphins sleep with only half of their brain at a time. This allows one eye to stay open and one half of the brain to stay alert, so the animal can surface to breathe and watch for predators while resting.",
     "According to the text, why can a sleeping dolphin still surface to breathe?",
     "Half of its brain stays alert while the other half rests.",
     ["It sleeps only once a week.", "It keeps both eyes open.", "It rests on the ocean floor."],
     "The text explains that half of the brain stays alert."),
    (CID, 2, "A recent analysis of subway ridership shows that weekday trips have recovered to about 80 percent of their earlier levels, while weekend trips have exceeded them. Transit officials suggest that as more people work from home on some days, riders are using the system for errands and outings rather than for commuting alone.",
     "Which choice best states the main idea of the text?",
     "Subway use has shifted in pattern, with weekends now busier than before even as weekdays remain lower.",
     ["Subway ridership has fallen to a record low.", "Weekend trips are more expensive than weekday trips.", "Transit officials plan to close the subway on weekends."],
     "The data show weekday ridership below earlier levels and weekend ridership above."),

    # -------------------------------------------------------- Command of Evidence
    (COE, 2, "A student claims that coastal cities are warming more slowly than inland cities. The student has the following data: Over the past 50 years, the average annual temperature rose by 1.1°C in Coastal City, 1.9°C in Inland City A, and 2.2°C in Inland City B.",
     "Which choice most effectively uses data from the text to support the student's claim?",
     "Coastal City's temperature rose by 1.1°C, a smaller increase than the 1.9°C and 2.2°C increases in the inland cities.",
     ["Inland City B's average temperature is higher than Coastal City's.", "All three cities experienced warming over the 50-year period.", "Inland City A warmed by 0.3°C less than Inland City B."],
     "Only the correct choice compares the coastal increase with the inland increases, which is what the claim is about."),
    (COE, 3, "Historian Elena Marsh argues that the village's decline began well before the railroad bypassed it. Records show that the village's population fell from 1,200 in 1860 to 740 in 1880, while the railroad's alternate route opened in 1890.",
     "Which choice best describes how the records support Marsh's argument?",
     "The population fell significantly before the railroad's alternate route opened.",
     ["The village had a larger population than nearby towns.", "The railroad opened in the same decade as the census.", "The population rose after 1890."],
     "The drop from 1,200 to 740 happened before 1890, so the decline predates the bypass."),
    (COE, 2, "Researchers claim that a certain fertilizer increases corn yield. In their experiment, plots treated with the fertilizer produced an average of 180 bushels per acre, while untreated plots under identical conditions produced an average of 150 bushels per acre.",
     "Which choice best describes data from the experiment that support the researchers' claim?",
     "Treated plots produced more bushels per acre than untreated plots under identical conditions.",
     ["Untreated plots produced 150 bushels per acre.", "The experiment was conducted on corn.", "Both kinds of plots were measured in bushels."],
     "Only the comparison between treated and untreated plots supports the claim that the fertilizer raises yield."),
    (COE, 1, "A student is writing about the novel's setting. She wants to support the claim that the author portrays the town as isolated.",
     "Which quotation from the novel would best support the student's claim?",
     "\"The nearest neighbor lived forty miles of dirt road away, and in winter even that road disappeared.\"",
     ["\"Every Sunday the whole town gathered at the long table behind the church.\"", "\"Maya had always thought the harvest festival was the best day of the year.\"", "\"The mayor's house, painted yellow, stood at the corner of Elm Street.\""],
     "Only the forty-mile road that vanishes in winter conveys isolation."),
    (COE, 3, "Marine biologist Dr. Lee claims that the reef's coral cover declined mainly because of rising water temperatures rather than pollution. Survey data show that coral cover dropped by 40 percent in both a heavily polluted bay and a pristine, protected bay over the same ten-year period, during which water temperature rose by 1.5°C in both locations.",
     "Which choice best describes how the survey data support Dr. Lee's claim?",
     "The coral decline occurred equally in polluted and unpolluted locations while temperature rose in both.",
     ["The polluted bay lost more coral than the pristine bay.", "Coral cover has been measured for ten years.", "The temperature rise was larger in the polluted bay."],
     "Equal declines despite different pollution levels, alongside the shared temperature rise, support the temperature explanation."),
    (COE, 2, "A student claims that the poet's later work is more optimistic than her earlier work. The student has gathered lines from two of her poems.",
     "Which pair of quotations best supports the student's claim?",
     "Earlier: \"The field lay barren under a sky that promised nothing.\" Later: \"The field woke green, and every cloud carried a promise.\"",
     ["Earlier: \"The river ran quietly past the old mill.\" Later: \"The river ran quietly past the new bridge.\"", "Earlier: \"The field woke green, and every cloud carried a promise.\" Later: \"The field lay barren under a sky that promised nothing.\"", "Earlier: \"She walked home alone.\" Later: \"She walked home at dusk.\""],
     "The earlier quote is bleak and the later one hopeful, which matches the claim of growing optimism."),
    (COE, 3, "Anthropologist Lila Chen proposes that the ancient settlement was abandoned because its water source dried up, not because of invasion. Excavations revealed no weapons, burn layers, or fortifications at the site, while sediment analysis showed that the nearby stream bed was dry by the time the settlement was emptied.",
     "Which finding, if true, would most directly weaken Chen's proposal?",
     "Burned buildings and arrowheads were found throughout the settlement's final layer.",
     ["The settlement was larger than neighboring settlements.", "The stream bed contains fine sediment.", "Pottery at the site was made from local clay."],
     "Evidence of burning and weapons would support invasion and so undermine the drying-up explanation."),
    (COE, 1, "A student is summarizing a report on school start times. The student wants to support the claim that later start times can improve attendance.",
     "Which finding from the report would best support the student's claim?",
     "After one district moved its start time from 7:30 a.m. to 8:30 a.m., the number of students absent each day fell by 12 percent.",
     ["Many districts have school start times before 8:00 a.m.", "Teenagers typically need between eight and ten hours of sleep.", "Some districts chose to keep their start times unchanged."],
     "Only the drop in absences after the later start directly links start time to attendance."),
    (COE, 2, "A student argues that urban green spaces improve residents' well-being. In one survey, residents living within 500 meters of a park reported an average well-being rating of 7.4 out of 10, while residents living more than 2 kilometers from any park reported an average rating of 6.1.",
     "Which choice most effectively uses data from the survey to support the student's argument?",
     "Residents near parks reported higher average well-being (7.4) than residents far from parks (6.1).",
     ["Well-being was rated on a scale of 10.", "Some residents live more than 2 kilometers from a park.", "Parks vary in size from city to city."],
     "The comparison of ratings by distance to a park supports the claim."),
    (COE, 3, "Economist Karim Aziz claims that the town's new factory raised local wages. Records show that average hourly pay in the town was $14.20 before the factory opened and $16.80 after, whereas pay in a similar nearby town with no new factory rose from $14.10 to $14.60 over the same period.",
     "Which choice best explains why the nearby town's data strengthen Aziz's claim?",
     "They suggest that the larger wage increase in the factory town was unlikely to be caused by general economic trends alone.",
     ["They prove that no wage increase occurred in the nearby town.", "They show that the nearby town's factory closed.", "They indicate that the two towns have identical populations."],
     "A comparison town provides a baseline; its much smaller rise suggests the factory contributed to the larger increase."),

    # ------------------------------------------------------------------ Inferences
    (INF, 2, "Researchers placed identical seedlings in two greenhouses. In the first, a fan gently moved the air several hours a day; in the second, the air stayed still. After a month, the seedlings in the first greenhouse had noticeably thicker stems. These results suggest that ______",
     "Which choice most logically completes the text?",
     "gentle movement of air may encourage plants to develop stronger stems.",
     ["fans are necessary for seeds to sprout.", "seedlings grow faster in the dark than in the light.", "thicker stems always produce larger fruit."],
     "Only the first choice follows from the single difference between the greenhouses (moving air)."),
    (INF, 1, "The bakery sells out of its sourdough loaves by ten o'clock every morning, even on days when it bakes twice as many loaves as usual. This suggests that ______",
     "Which choice most logically completes the text?",
     "demand for the sourdough is high enough that even larger batches sell quickly.",
     ["customers dislike the sourdough.", "the bakery should stop making sourdough.", "the bakery opens later than other shops."],
     "Selling out even with doubled supply indicates strong demand."),
    (INF, 3, "Scientists studying a remote island found that native birds there show no fear of humans, allowing researchers to approach within arm's reach. Birds on nearby continents typically flee at distances of tens of meters. One reasonable inference is that the island birds ______",
     "Which choice most logically completes the text?",
     "evolved without large land predators and therefore never developed a strong fear response.",
     ["are smarter than continental birds.", "cannot see people approaching.", "have been trained by the researchers."],
     "Lack of fear is most plausibly explained by the absence of predators that would have selected for wariness."),
    (INF, 2, "Medieval scribes occasionally wrote notes in the margins of manuscripts, such as complaints about the cold or the poor quality of ink. Because these notes were never intended for readers, historians consider them especially valuable, since they ______",
     "Which choice most logically completes the text?",
     "reveal the scribes' everyday experiences in a way that formal text does not.",
     ["prove that the manuscripts were forged.", "show that scribes could not write well.", "list the rules scribes had to follow."],
     "Unintended private remarks capture daily life candidly, which is what makes them valuable."),
    (INF, 2, "A city replaced its traditional streetlights with LED lights that use half as much electricity. In the first year, however, the city's total electricity bill for street lighting barely changed. This outcome would be most easily explained if ______",
     "Which choice most logically completes the text?",
     "the city installed twice as many lights as it had before.",
     ["LED lights are brighter than traditional lights.", "the city's electricity rates fell by half.", "traditional lights last longer than LED lights."],
     "If lights doubled in number while each used half the power, the total would stay about the same."),
    (INF, 3, "Paleontologists found fossilized tracks showing that an unusually large number of dinosaurs walked in the same direction along an ancient lakeshore. Some argue that the animals were migrating together. Others point out that the tracks all lead toward a patch of mud that would have held fresh water. If the second group is correct, then the fossils ______",
     "Which choice most logically completes the text?",
     "may reflect many animals independently seeking water rather than a coordinated migration.",
     ["prove that the dinosaurs were hunting each other.", "show that the lake had no fresh water.", "indicate that the dinosaurs could not walk far."],
     "If they were heading to water, the shared direction could result from separate animals with the same goal."),
    (INF, 1, "Every spring, the lake near Maria's house fills with migrating geese. This year, however, the geese did not come, and Maria noticed that the lake was still frozen in late April. It is likely that the geese ______",
     "Which choice most logically completes the text?",
     "stayed away because the ice made the lake unusable.",
     ["were frightened by Maria.", "prefer cold weather.", "migrate only in winter."],
     "The still-frozen lake is the likely reason the geese were absent."),
    (INF, 2, "Linguists have observed that the more often a word is used in everyday speech, the more likely it is to be short. For example, 'is' and 'the' are far shorter than 'photosynthesis.' This pattern suggests that speakers tend to ______",
     "Which choice most logically completes the text?",
     "shorten frequently used words over time to communicate more efficiently.",
     ["avoid using common words.", "invent long words to sound impressive.", "forget rare words quickly."],
     "Frequent use correlates with brevity, which suggests efficiency-driven shortening."),
    (INF, 3, "When a team of ecologists removed every spider from several small islands, the number of plant-eating insects there rose sharply within a season, and the plants on those islands showed more leaf damage than plants on islands where spiders remained. This suggests that spiders ______",
     "Which choice most logically completes the text?",
     "help limit plant damage by preying on plant-eating insects.",
     ["feed mainly on leaves.", "cannot survive on islands.", "reduce the number of plants."],
     "Without spiders, insects increased and damage rose, so spiders restrain the insects that damage plants."),
    (INF, 2, "A recent survey of public libraries found that branches that added late-night hours saw a rise in visits by adults who work during the day, but little change in visits by retirees. Library officials concluded that the new hours ______",
     "Which choice most logically completes the text?",
     "primarily benefited patrons whose work schedules had made daytime visits difficult.",
     ["discouraged retirees from reading.", "were unpopular with everyone.", "caused the libraries to lose money."],
     "The increase was among daytime workers, so the hours mainly helped those with schedule conflicts."),
    (INF, 3, "Sound travels about four times faster through water than through air. Because of this, a whale's call can be detected by other whales hundreds of kilometers away. It follows that the ocean, compared with the open air, is ______",
     "Which choice most logically completes the text?",
     "a more effective medium for long-distance communication by sound.",
     ["a quieter place than a forest.", "unsuitable for communication.", "less crowded with animal life."],
     "Faster travel allows calls to be detected over great distances."),
]
