# Original SAT-style Reading & Writing items, part 2:
# Standard English Conventions and Expression of Ideas.

BND = "Boundaries"
FSS = "Form, Structure & Sense"
TRN = "Transitions"
RHS = "Rhetorical Synthesis"

STD = "Which choice completes the text so that it conforms to the conventions of Standard English?"
TRANS = "Which choice completes the text with the most logical transition?"
SYN = "Which choice most effectively uses relevant information from the notes to accomplish this goal?"

PART2 = [
    # ---------------------------------------------------------------- Boundaries
    (BND, 1, "The marine biologist collected samples from three tide pools ______ then examined each one under a microscope.",
     STD, "pools; she", ["pools, she", "pools she", "pools: she"],
     "Two independent clauses need a semicolon or a comma plus a conjunction. A comma alone makes a comma splice; with no punctuation it is a run-on; and nothing here calls for a colon."),
    (BND, 1, "Before the storm arrived, the crew secured the boats, covered the equipment, ______ moved the supplies to higher ground.",
     STD, ", and", ["; and", ": and", ", and,"],
     "Items in a series are separated by commas, with a comma before the final 'and.' A semicolon or colon is not appropriate, and the extra comma after 'and' interrupts the verb."),
    (BND, 2, "The museum's newest acquisition, a seventeenth-century map of the Atlantic coast ______ is now on display in the east gallery.",
     STD, "coast,", ["coast", "coast;", "coast:"],
     "The appositive 'a seventeenth-century map of the Atlantic coast' is nonessential and opened with a comma, so it must close with a comma before the verb."),
    (BND, 2, "Maya had only one goal for the weekend ______ finish her science project.",
     STD, "weekend: finish", ["weekend; finish", "weekend, finish", "weekend finish"],
     "A colon after a complete clause can introduce what the goal is. A semicolon needs a complete clause on both sides, and a comma alone would create a splice."),
    (BND, 2, "The author of the novel, who grew up in a small coastal town ______ often writes about the sea.",
     STD, "town,", ["town", "town;", "town:"],
     "The nonessential clause 'who grew up in a small coastal town' opens with a comma after 'novel' and must close with a matching comma before the verb."),
    (BND, 1, "Although the experiment failed ______ the team learned several useful lessons.",
     STD, "failed,", ["failed;", "failed:", "failed"],
     "A comma follows an introductory dependent clause that begins with 'Although.'"),
    (BND, 3, "The committee reviewed three proposals ______ a plan to expand the library, a plan to repair the gym, and a plan to build a new field.",
     STD, "proposals:", ["proposals;", "proposals and", "proposals"],
     "A colon after a complete clause introduces the list of proposals. A semicolon would have to be followed by an independent clause."),
    (BND, 2, "The oldest tree in the park is a giant sequoia ______ it is more than two thousand years old.",
     STD, "sequoia; it", ["sequoia, it", "sequoia it", "sequoia: and it"],
     "Two independent clauses can be joined by a semicolon. A comma alone makes a splice, and no punctuation makes a run-on."),
    (BND, 2, "The final exhibit\u2014a collection of letters written by soldiers ______ drew the longest lines.",
     STD, "soldiers\u2014", ["soldiers,", "soldiers;", "soldiers:"],
     "A nonessential phrase opened with a dash must be closed with a dash; mixing a dash with a comma, semicolon, or colon is incorrect."),
    (BND, 1, "Ravi's favorite subjects are ______ chemistry, history, and music.",
     STD, "are chemistry", ["are: chemistry", "are, chemistry", "are; chemistry"],
     "No punctuation should separate a linking verb ('are') from its complement."),
    (BND, 3, "The study's lead author explained why the data were surprising ______ the results contradicted decades of earlier findings.",
     STD, "surprising: the", ["surprising, the", "surprising the", "surprising: and the"],
     "A colon after a complete clause introduces an explanation; a comma alone splices two clauses, and no punctuation runs them together."),
    (BND, 2, "The tour stops in Lima, Peru ______ Quito, Ecuador; and Bogot\u00e1, Colombia.",
     STD, "Peru;", ["Peru,", "Peru:", "Peru"],
     "When items in a series already contain commas, semicolons separate the items so the series is clear."),
    (BND, 1, "The book ______ I borrowed from the library was due on Friday.",
     STD, "book I", ["book, I", "book; I", "book: I"],
     "'I borrowed from the library' is an essential clause identifying which book, so no punctuation is used."),
    (BND, 3, "The trail was closed for repairs ______ however, hikers could still reach the lake by the old road.",
     STD, "repairs;", ["repairs,", "repairs:", "repairs"],
     "A conjunctive adverb like 'however' joining two independent clauses takes a semicolon before it and a comma after it."),

    # --------------------------------------------------- Form, Structure & Sense
    (FSS, 1, "Each of the students ______ required to submit a final report by Friday.",
     STD, "is", ["are", "were", "have been"],
     "'Each' is singular, so it takes the singular verb 'is.'"),
    (FSS, 1, "The researchers ______ their findings at the conference last month.",
     STD, "presented", ["presents", "will present", "have presenting"],
     "'Last month' signals the past tense."),
    (FSS, 2, "The collection of rare coins, which includes pieces from three continents, ______ valued at over a million dollars.",
     STD, "is", ["are", "were being", "have been"],
     "The subject is 'collection,' which is singular; the phrase between commas does not change that."),
    (FSS, 2, "The students handed in ______ essays before the bell rang.",
     STD, "their", ["its", "there", "they're"],
     "The plural 'students' takes the plural possessive 'their.'"),
    (FSS, 2, "Neither the coach nor the players ______ expecting the schedule change.",
     STD, "were", ["was", "is", "has been"],
     "With 'neither...nor,' the verb agrees with the nearer subject, 'players,' which is plural."),
    (FSS, 1, "The new library is larger than ______ in the next town.",
     STD, "the one", ["those", "it", "that one is"],
     "'The one' refers back to a single library for a logical comparison."),
    (FSS, 2, "By the time the rescue team arrived, the hikers ______ for nearly six hours.",
     STD, "had been waiting", ["were waiting", "waited", "have waited"],
     "The past perfect 'had been waiting' shows an action that began before another past event (the arrival)."),
    (FSS, 2, "The wolf lifted ______ head and howled at the moon.",
     STD, "its", ["it's", "their", "his or hers"],
     "'Its' is the possessive form of 'it'; 'it's' means 'it is,' and 'their' is plural."),
    (FSS, 2, "Because of its long, flexible neck, the giraffe can reach leaves that ______ out of reach for most other animals.",
     STD, "are", ["is", "was", "has been"],
     "The plural 'leaves' requires 'are,' and the sentence is in the present tense."),
    (FSS, 1, "Ms. Patel, along with her two assistants, ______ preparing the exhibit.",
     STD, "is", ["are", "were", "have been"],
     "The subject is 'Ms. Patel'; 'along with her two assistants' does not make it plural."),
    (FSS, 3, "Having finished the experiment, ______",
     "Which choice completes the text so that it conforms to the conventions of Standard English?",
     "the students recorded the results in a notebook.",
     ["the results were recorded in a notebook by them.", "a notebook was where the results were recorded.", "the recording of results was done by the students."],
     "The introductory participial phrase 'Having finished the experiment' must modify the people who finished it: 'the students.'"),
    (FSS, 2, "The twins ______ their grandmother's house every summer since they were five.",
     STD, "have visited", ["visit", "visited", "will visit"],
     "'Every summer since they were five' calls for the present perfect, an action that began in the past and continues."),
    (FSS, 1, "Of the two bridges, the old stone bridge is the ______.",
     STD, "narrower", ["narrowest", "most narrow", "more narrower"],
     "Comparing two items uses the comparative form 'narrower.'"),
    (FSS, 3, "The city council, in an effort to ease congestion, ______ to add bus lanes on three major roads.",
     STD, "voted", ["vote", "voting", "were voting"],
     "The singular subject 'council' takes 'voted'; the phrase set off by commas does not change the subject."),
    (FSS, 2, "Neither of the answers ______ correct.",
     STD, "is", ["are", "were", "have been"],
     "'Neither' is singular."),
    (FSS, 2, "The scientist's goal was to measure ______ much carbon the forest absorbed each year.",
     STD, "how", ["what", "that", "which"],
     "'How much' correctly introduces the quantity being measured."),
    (FSS, 3, "Unlike the rainfall in coastal regions, ______ in the mountains arrives mostly as snow.",
     STD, "the rainfall", ["it", "those", "which"],
     "The comparison must be between like things: rainfall in coastal regions and rainfall in the mountains."),
    (FSS, 1, "Last summer, my brother ______ a ten-mile hike in less than three hours.",
     STD, "completed", ["completes", "has completed", "will complete"],
     "'Last summer' signals the simple past."),

    # -------------------------------------------------------------- Transitions
    (TRN, 1, "The first prototype of the electric scooter was heavy and slow. ______ the second version was light enough to carry and reached twice the speed.",
     TRANS, "By contrast,", ["For example,", "Similarly,", "As a result,"],
     "The second version differs from the first, so a contrast transition fits."),
    (TRN, 2, "Many birds migrate south for the winter. ______ some species, such as the Arctic tern, travel nearly the length of the planet.",
     TRANS, "In fact,", ["However,", "Otherwise,", "Meanwhile,"],
     "The second sentence extends and intensifies the first, so 'In fact' fits."),
    (TRN, 2, "The restaurant's menu had hardly changed in thirty years. ______ regular customers were surprised when the owner announced a complete redesign.",
     TRANS, "Consequently,", ["Instead,", "For instance,", "Alternatively,"],
     "The unchanged menu is the reason regulars were surprised; the redesign was unexpected as a result."),
    (TRN, 1, "Lena practiced the piano for an hour every day. ______ she won first place at the regional competition.",
     TRANS, "As a result,", ["In contrast,", "For example,", "Nevertheless,"],
     "Her practice led to her winning, so a cause-and-effect transition is best."),
    (TRN, 2, "Wind turbines produce electricity without burning fuel. ______ they can disrupt bird flight paths if built in the wrong place.",
     TRANS, "However,", ["Therefore,", "Likewise,", "Specifically,"],
     "The second sentence introduces a drawback, contrasting with the benefit in the first."),
    (TRN, 3, "Scientists once believed that Pluto was a typical planet. ______ the discovery of many similar objects in the outer solar system prompted astronomers to reconsider.",
     TRANS, "Later,", ["Therefore,", "For example,", "In other words,"],
     "The sentences describe a sequence of events: a past belief followed by a later discovery."),
    (TRN, 2, "The new highway reduced travel time between the two cities by half. ______ it brought a surge of visitors to businesses along the route.",
     TRANS, "Moreover,", ["Nevertheless,", "Instead,", "Conversely,"],
     "The second sentence adds a further benefit, so 'Moreover' fits."),
    (TRN, 3, "Some critics argued that the novel's ending was rushed. ______ the author has said that she wrote the ending first and built the rest of the book toward it.",
     TRANS, "Yet", ["Thus", "For instance", "In addition"],
     "The author's statement pushes back on the critics' view, so a contrast is needed."),
    (TRN, 1, "Most mammals give birth to live young. ______ the platypus lays eggs.",
     TRANS, "The platypus, however,", ["The platypus, similarly,", "The platypus, therefore,", "The platypus, for instance,"],
     "The platypus is an exception to the general statement, so a contrast is logical."),
    (TRN, 2, "Several students suggested changing the school's lunch schedule. ______ the principal agreed to test a new schedule for one month.",
     TRANS, "In response,", ["On the other hand,", "In comparison,", "Regardless,"],
     "The principal's action follows from, and responds to, the students' suggestions."),

    # ------------------------------------------------------ Rhetorical Synthesis
    (RHS, 2, "While researching a topic, a student has taken the following notes:\n• The monarch butterfly migrates up to 3,000 miles each fall.\n• It travels from Canada and the northern United States to central Mexico.\n• No single butterfly makes the round trip; it takes several generations to return north.\n• The trip is guided by the sun's position and Earth's magnetic field.",
     "The student wants to emphasize the length of the migration. " + SYN,
     "The monarch butterfly's annual migration, up to 3,000 miles from Canada and the northern United States to central Mexico, is so long that it takes several generations to complete the round trip.",
     ["Monarch butterflies are guided by the sun's position and Earth's magnetic field.", "Monarch butterflies migrate in the fall, though they do not all make the round trip.", "Monarch butterflies, which live in Canada and the northern United States, also travel to Mexico."],
     "Only the correct choice foregrounds distance (3,000 miles) and ties it to the multi-generation round trip."),
    (RHS, 1, "While researching a topic, a student has taken the following notes:\n• The Eiffel Tower was completed in 1889.\n• It was built for the World's Fair in Paris.\n• It is 330 meters tall.\n• It was the tallest man-made structure in the world until 1930.",
     "The student wants to explain why the tower was built. " + SYN,
     "The Eiffel Tower was built for the 1889 World's Fair in Paris.",
     ["The Eiffel Tower is 330 meters tall.", "The Eiffel Tower was the tallest man-made structure in the world until 1930.", "The Eiffel Tower was completed in 1889 and remains popular today."],
     "Only the correct choice states the purpose for which it was built."),
    (RHS, 2, "While researching a topic, a student has taken the following notes:\n• Sourdough bread uses a fermented starter instead of commercial yeast.\n• The starter contains wild yeast and bacteria.\n• These bacteria give sourdough its tangy flavor.\n• Sourdough often stays fresh longer than yeast bread.",
     "The student wants to explain what gives sourdough its distinctive taste. " + SYN,
     "The bacteria in the wild-yeast starter that sourdough uses give the bread its tangy flavor.",
     ["Sourdough often stays fresh longer than bread made with commercial yeast.", "Sourdough uses a fermented starter instead of commercial yeast.", "Sourdough is a type of bread that many people enjoy."],
     "Only the correct choice links the taste to its cause, the bacteria."),
    (RHS, 2, "While researching a topic, a student has taken the following notes:\n• Basalt is a dark volcanic rock.\n• It forms when lava cools quickly.\n• Granite is a light-colored rock.\n• Granite forms when magma cools slowly beneath Earth's surface.",
     "The student wants to contrast how basalt and granite form. " + SYN,
     "Basalt forms when lava cools quickly, whereas granite forms when magma cools slowly beneath Earth's surface.",
     ["Basalt is dark and granite is light.", "Both basalt and granite are rocks that form from cooled molten material.", "Basalt forms from lava, and magma is found beneath Earth's surface."],
     "Only the correct choice contrasts the cooling rates and settings."),
    (RHS, 3, "While researching a topic, a student has taken the following notes:\n• Author Zora Neale Hurston collected folktales in Florida in the 1920s and 1930s.\n• Her book Mules and Men was published in 1935.\n• It presents stories exactly as speakers told them, in their own dialect.\n• Some earlier collectors had rewritten such stories in standard English.",
     "The student wants to explain what made Hurston's approach distinctive. " + SYN,
     "Unlike some earlier collectors who rewrote folktales in standard English, Hurston presented stories exactly as speakers told them, in their own dialect.",
     ["Hurston published Mules and Men in 1935.", "Hurston collected folktales in Florida during the 1920s and 1930s.", "Folktales were collected by many people before Hurston."],
     "Only the correct choice contrasts her method with earlier practice."),
    (RHS, 1, "While researching a topic, a student has taken the following notes:\n• The Pacific Crest Trail runs from Mexico to Canada.\n• It is about 2,650 miles long.\n• It passes through California, Oregon, and Washington.\n• Hikers usually need five months to complete it.",
     "The student wants to give a basic description of the trail's route and length. " + SYN,
     "The Pacific Crest Trail, about 2,650 miles long, runs from Mexico to Canada through California, Oregon, and Washington.",
     ["Hikers usually need about five months to complete the Pacific Crest Trail.", "The Pacific Crest Trail is popular with hikers in California.", "The Pacific Crest Trail is longer than most trails in the country."],
     "Only the correct choice gives route and length."),
    (RHS, 2, "While researching a topic, a student has taken the following notes:\n• Octopuses have three hearts.\n• Two hearts pump blood through the gills.\n• The third pumps blood to the rest of the body.\n• Octopus blood is blue because it contains copper.",
     "The student wants to explain the purpose of the octopus's multiple hearts. " + SYN,
     "An octopus has three hearts: two pump blood through the gills, and the third pumps blood to the rest of the body.",
     ["Octopus blood is blue because it contains copper.", "Octopuses are unusual animals with unusual body features.", "An octopus's third heart is larger than the other two."],
     "Only the correct choice states what each heart does."),
    (RHS, 3, "While researching a topic, a student has taken the following notes:\n• In 2019, a town installed solar panels on its public school roofs.\n• The panels cut the schools' electricity costs by 35 percent.\n• The savings paid for two new teaching positions.\n• Some residents had worried about the upfront cost of the project.",
     "The student wants to argue that the project was worthwhile despite its cost. " + SYN,
     "Although some residents worried about the upfront cost, the solar panels cut the schools' electricity costs by 35 percent, and the savings paid for two new teaching positions.",
     ["In 2019, a town installed solar panels on its public school roofs.", "Some residents worried about the cost of installing solar panels.", "The solar panels were installed on school roofs, and two teachers were hired."],
     "Only the correct choice acknowledges the cost concern and answers it with concrete benefits."),
    (RHS, 1, "While researching a topic, a student has taken the following notes:\n• The kakapo is a flightless parrot from New Zealand.\n• It is nocturnal.\n• There are fewer than 300 kakapo alive today.\n• Conservationists monitor every bird.",
     "The student wants to emphasize how endangered the kakapo is. " + SYN,
     "With fewer than 300 left alive, every kakapo, a flightless parrot from New Zealand, is monitored by conservationists.",
     ["The kakapo is a nocturnal parrot from New Zealand.", "The kakapo cannot fly.", "Many parrots are kept as pets."],
     "Only the correct choice conveys scarcity (fewer than 300) and the extreme response to it."),
    (RHS, 2, "While researching a topic, a student has taken the following notes:\n• Typewriters were widely used in offices from the 1880s through the 1980s.\n• The QWERTY layout was designed to reduce jams.\n• Computers eventually replaced typewriters in most offices.\n• The QWERTY layout is still used on computer keyboards.",
     "The student wants to show how a feature of an older technology has persisted. " + SYN,
     "Although computers replaced typewriters in most offices, the QWERTY layout, designed to reduce typewriter jams, is still used on computer keyboards.",
     ["Typewriters were widely used in offices from the 1880s through the 1980s.", "Computers eventually replaced typewriters in most offices.", "The QWERTY layout was designed in the nineteenth century."],
     "Only the correct choice connects the old design to its present-day use."),
]
